# ==================================================
# OIDC Configuration for PeopleSoft
# ==================================================

issuer=https://login.microsoftonline.com/<tenant_id>/v2.0
client.id=
client.secret=
redirect.uri=http://localhost:8000/psc/ps/EMPLOYEE/HRMS/c/NUI_FRAMEWORK.PT_LANDINGPAGE.GBL

scope=openid profile email
username.claim=preferred_username
header.name=X-PS-USER

# iat check at login only — does NOT affect active PS sessions
max.token.age.seconds=600

# Force PKCE — Azure supports it but doesn't advertise in discovery doc
force.pkce=true

#Turn off in prod
debug=true
